site_name: My Bookmarks
repo_url: https://github.com/TetsuOu/Bookmarks
repo_name: TetsuOu/Bookmarks

nav:
    - Introduction: 'index.md'
    - SiteNavigation: 'https://TetsuOu.github.io/SiteNavigation/'
    - Program:  
        - Android: 'Program/Android.md'
        - C/C++: 'Program/C++.md'
        - Java: 'Program/Java.md'
        - Python: 'Program/Python.md'
        - Windows: 'Program/Windows.md'
    - Study:
        - Language: 'Study/Language.md'
        - Computer Science: 'Study/ComputerScience.md'
    - Life:
        - Growing: 'Life/Growing.md'
 
copyright: Copyright &copy; 2023 TetsuOu


theme: 
    name: material
    favicon: img/favicon.ico
    features:
        - navigation.tabs
    icon:
        repo: fontawesome/brands/github

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/TetsuOu
          name: TetsuOu
    
